baseURL = 'https://zippy-cupcake-c876f6.netlify.app/'
languageCode = 'de-de'
title = 'Bewegungsmelder Osnabrück'

[module]
[[module.imports]]
path = "github.com/theNewDynamic/gohugo-theme-ananke"

[params]
author = "Bewegungsmelder"
description = "Termine und Veranstaltungen in Osnabrück"
