baseURL = "/"
languageCode = "de-de"
title = "Bewegungsmelder Osnabrück"
theme = "ananke"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
    # Diese Zeile ist neu und fixt den "upgrade" Fehler:
    version = "v2.12.1"
