baseURL = "/"
languageCode = "de-de"
title = "Bewegungsmelder Osnabrück"
theme = "ananke" # Sagt Hugo, welches Theme es nutzen soll

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
